### PR TITLE
Major cleanup: python versions, versions pinned and github actions

### PR DESCRIPTION
**Pull request by gforcada**
Finally I have some time to spend on setting a new base for `flake8-builtins` future ✨ 

- python 2.7 and 3.6 support was removed, which allows to remove quite some code
- version pins on `requirements.txt` were updated, which will remove the security warnings GitHub is displaying
- GitHub actions was updated, to ensure the supported python versions are actually working

I always like to create lots of commits with each doing one specific topic, so although the changes are quite a lot, they are all (hopefully) isolated 🤞🏾 😄 

@cclauss @gsingh93 you might want to have a look. I will review and merge your PR on top of this one, if I manage to make this one pass CI, my skills level on GitHub actions is rather low 😓 today is already improving this 😄

### CODE REVIEW

**Comment by cclauss** [comment]
Have you used https://pre-commit.com ?  That would have formatting tools like black, isort, pyupgrade, autoflake reformat the code as its being committed locally.  It saves roundtrips.

**Comment by gsingh93** [comment]
Regarding the CI failure, I see in the README for [typed_ast](https://github.com/python/typed_ast): "Due to reliance on certain C APIs, this library does not build on and there are no plans to support PyPy."

**Comment by gforcada** [comment]
@gsingh93 thanks, yes, I noticed that, I'm fixing this and making the github workflow file a bit more understandable and I think I will merge it in a bit 😄

**Comment by gforcada** [comment]
@gsingh93 fortunately we can avoid the `type_ast` problem by using a pypy version that targets python 3.8+ 🎉

**Comment by gforcada** [comment]
I had to remove `hypothesis` tests, as they were running mostly fine locally, but failing at running on GitHub actions 😕 

We might add them later back, I don't want to hold this any longer 👍🏾

**Pull request merged**
