### PR TITLE
make black and isort mandatory tests

### PR DESCRIPTION
**Pull request by cclauss**
```
black --skip-string-normalization .
isort --profile black .
```

### CODE REVIEW

**Comment by gforcada** [comment]
Thanks! but as you see I very much follow black completely but I have a strong preference for single quotes. Fortunately black has an option to ignore those `skip-string-normalization` would you mind adding that so that the diff is veeeeeery much reduced? TIA!! 🙇🏾

**Comment by gforcada** [comment]
thanks! would you mind squashing both commits together? so that history/blame later on is not confused by them? 👍🏾

**Comment by gsingh93** [comment]
@gforcada any chance you could merge this? I have to disable auto-formatting in my editor while making code changes, as it's adding in a bunch of unrelated `black`/`isort` changes as well.

**Comment by gforcada** [comment]
@cclauss thanks for the changes again, and @gsingh93 for the ping, I'm rather busy these days 😅 merging! 😄

**Pull request merged**
