### PR TITLE
Adds python3.8 support with AnnAssign and NamedExpr

### LINKED ISSUE #49: Names that use `AnnAssign` are not supported
Reproduction: 
1. `echo 'list: int = 1' > ex.py`
2. `flake8 ex.py`

It exists with status code `0`.

I expect it to work the same as `list = 1` which produces:

```
» flake8 ex.py 

ex.py

  1:1      A001  "list" is a python builtin and is being shadowed, consider renaming the variable
  list = 1
  ^
```

The problem is in this line: https://github.com/gforcada/flake8-builtins/blob/master/flake8_builtins.py#L81 Because it does not check `ast.AnnAssign`

### LINKED ISSUE #50: Walrus operator is not supported
There are several things to add:

1. `ast.NamedExpr` support
2. `python3.8` to the test case
3. `python3.8` classifiers
4. Specific tests for cases like `(list := 1)`

Related https://github.com/wemake-services/wemake-python-styleguide/issues/1138

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #50 
Closes #49

### CODE REVIEW

**Comment by sobolevn** [comment]
@gforcada why is CI disabled? I cannot find my build 😢

**Comment by gforcada** [comment]
@sobolevn no idea, I did not disable them on purpose, I will try to see what's going on

**Comment by gforcada** [comment]
No idea why it is not reported here, but the travis build is here: https://travis-ci.org/github/gforcada/flake8-builtins/builds/661968564 seems that we have a problem with cffi on python 3.8 :confused:

**Comment by sobolevn** [comment]
@gforcada why do we need `cffi`?

**Comment by gforcada** [comment]
No idea, I'm fixing it on #53 :crossed_fingers:

**Pull request merged**
