### PR TITLE
Introduce A006 for lambda shadowing

### PR DESCRIPTION
**Pull request by cielavenir**
I added this to run_tests.py:

```
def test_lambda_argument_message():
    source = 'takefirst = lambda list: list[0]'
    check_code(source, 'A002')
```

Then I see this:

```
>       assert len(return_statements) == len(expected_codes)
E       AssertionError: assert 0 == 1
E        +  where 0 = len([])
E        +  and   1 = len(['A002'])
```

This MR tries to fix it.

Reproduced in main/Python3, 1.5/Python3 and 1.5/Python2.

/cc @felixvd @ntohge

### CODE REVIEW

**Comment by gforcada** [comment]
Thanks, for taking the time to write the PR! 🙇🏾 😄 

Though, I'm not sure if `lambda`'s are really a use case for flake8-builtins 🤔 

I mean, if you do:

```python
my_list = list()
my_list.append(1)
my_list.append(2)
my_list.append(3)

list = [1,2,3]

another_list = list()
```

This last line breaks due to having reassigned the builtin `list` to an actual list.

But if we do the same with a lambda:

```python
one_list = list()
one_list.append(1)
one_list.append(2)
one_list.append(3)

my_lambda = lambda list: list[0]

my_lambda(one_list) # returns 1

second_list = list()
second_list.append(4)
second_list.append(5)
second_list.append(6)

my_lambda(second_list) # returns 4
```

This still works... let me think a bit more about it before deciding 🤔

**Comment by felixvd** [comment]
> `my_lambda = lambda list: list[0]`

I agree this isn't the same level of risk as other A002 errors , but it doesn't exactly look like great practice either.

**Comment by gforcada** [comment]
Indeed, but then, maybe we could use a new error code `A005` for it? 🤔 It means a bit more work though 😕

**Comment by cielavenir** [comment]
@gforcada done

(sorry that check_function_definition and check_lambda_definition have duplicated code)

**Comment by felixvd** [comment]
@cielavenir Let's update the Readme too:

```rst

A005:
  A lambda argument is shadowing a Python builtin.
```

**Comment by cielavenir** [comment]
@felixvd done.

**Comment by gforcada** [comment]
🙈 sorry! I just merged another contribution that added a `A005`, we should turn this into a `A006`. Would you mind updating the code? I can try myself to do it otherwise, though, I'm a bit busy as of late 😕

**Comment by cielavenir** [comment]
@gforcada merged main

**Comment by gforcada** [comment]
@cielavenir one last request, sorry! 🙏🏾 could you add a line on `CHANGES.rst` as well? 🍀 

With this it will be ready to get merged 😊

**Comment by cielavenir** [comment]
@gforcada done

**Comment by gforcada** [comment]
Thanks!! 😄 

The date change was not needed, I will revert it myself after the merge.

**Comment by gforcada** [comment]
... and `flake8-builtins==2.4.0` is released! 🎉

**Pull request merged**
