### PR TITLE
Bump pycodestyle version up to 2.4.0 and flake8 up to 3.6.0

### PR DESCRIPTION
**Pull request by borisuvarov**
I had some conflicts with other flake8 plugins due to outdated version of `pycodestyle`, hope this super tiny PR is going to help.

### CODE REVIEW

**Comment by gforcada** [comment]
@borisuvarov thanks for the pull request. I have no idea which problems you had with other flake8 plugins, but fixing the requirements.txt in this repo is not going to fix other plugins I'm afraid.

Nevertheless, as travis says that this is working, let's merge it, thanks!

**Comment by borisuvarov** [comment]
@gforcada Thanks Gil! Is it possible to create a new release, and push it to PyPI? Thanks in advance!

**Comment by gforcada** [comment]
@borisuvarov your merge request is the only change made since the last release, and as this is only modifying the ``requirements.txt`` of this package, it would be pointless to make a release.

``requirements.txt`` is not being used at all when ``flake8-builtins`` is used with ``flake8``.

What would be the purpose of making a new release that changes a file that is being used internally for the project but that is not used with the egg/wheel released from that project? :thinking: I might be missing something obvious to you it seems :sweat_smile:

**Comment by borisuvarov** [comment]
@gforcada My bad, I see now that the only dependency `flake8-builtins` have is the latest (unpinned) version of flake8, so my PR is not solving my problem with a failing graph of unpinned dependencies. :-) Sorry for bothering you.

**Comment by gforcada** [comment]
@borisuvarov no problem at all! :smile:

**Pull request merged**
