### PR TITLE
Adds kwonly and posonly args support, closes #54

### LINKED ISSUE #54: posonly arguments support
This code does not raise any violations:

```python
def some(list, /, arg): 
    ...
```

Because `/` posonly args are not checked. 
It is a thing since 3.8

I will send a PR after #52 is merged

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by gforcada** [comment]
@sobolevn 1.5.0 :tada: is out meanwhile, thanks for this further fixes and enhancements! :bowing_man:

**Comment by sobolevn** [comment]
Let's make this one into `1.5.1`, because technically it is a bugfix. What do you think?

**Comment by sobolevn** [comment]
@gforcada do you want to bump a `flake8-builtins` version in `wemake-python-styleguide`? Here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L63 🙂

**Comment by gforcada** [comment]
@sobolevn merged and released as 1.5.1 :tada:

**Comment by sobolevn** [comment]
Thanks!

**Pull request merged**
